// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20250629214100_Seeding Data for Difficulties and Regions")]
    partial class SeedingDataforDifficultiesandRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c1c803b-205b-4da1-98fb-d3ece044b7f5"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("ad00f16c-69e9-41f6-bc1e-924d2dbbe52a"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("18a21bc0-9507-4665-8286-a218a8f79320"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45d29a9c-3faa-47c1-8be4-2e0d6e4e0e34"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://images.app.goo.gl/2cGwTsEPehnAJMLp7"
                        },
                        new
                        {
                            Id = new Guid("7cebc750-6f2c-4e49-ab04-f9d07303cc7d"),
                            Code = "WLG",
                            Name = "Wellingtown",
                            RegionImageUrl = "https://images.app.goo.gl/SbyGgmxzdswDkMPe6"
                        },
                        new
                        {
                            Id = new Guid("1fa662ba-fec9-4688-a791-a51abfe46636"),
                            Code = "CC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://images.app.goo.gl/9UjWkwGkQTfSSoj18"
                        },
                        new
                        {
                            Id = new Guid("22595f86-fcc7-48db-a8a4-4c71e1d71a1c"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImageUrl = "https://images.app.goo.gl/Jy7TLKwa5wgQtUneA"
                        },
                        new
                        {
                            Id = new Guid("854434c7-eebc-42ae-b045-57a583cd7e10"),
                            Code = "BOP",
                            Name = "Bay Of Plenty",
                            RegionImageUrl = "https://images.app.goo.gl/mGiWkWDenNQ8eHEH6"
                        },
                        new
                        {
                            Id = new Guid("14bb6474-98af-4af9-82f3-b0f0ea032151"),
                            Code = "Northland",
                            Name = "NTL",
                            RegionImageUrl = "https://images.app.goo.gl/o4ATMn4Dotz5AH7n8"
                        },
                        new
                        {
                            Id = new Guid("edf6f527-0338-4cce-a920-13cc51e8fc8d"),
                            Code = "Nelson",
                            Name = "NSN",
                            RegionImageUrl = "https://images.app.goo.gl/9F8Ki6uD6swa1EJR7"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
